name: Daily Empty Commit

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  empty-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            token: ${{ secrets.PERSONAL_TOKEN }}
      - name: Fetch and rebase
        run: |
          git fetch origin main
          git rebase origin/main
      - name: Make empty commit
        run: |
          git config user.name "ZidanCorson"
          git config user.email "zidan.wang@bbc.co.uk"
          git commit --allow-empty -m "chore: daily empty commit"
      - name: Push commit
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git push https://ZidanCorson:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ github.repository }}.git main
